deployments:
  giropops-senhas:
    name: "giropops-senhas-helm"
    image: "linuxtips/giropops-senhas:1.0"
    replicas: 3
    ports:
      - port: 5000
      - port: 8088
    labels:
      app: "giropops-senhas"
      env: "labs"
      live: "false"
    resources: 
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  redis:
    name: "redis-helm"
    image: "redis"
    replicas: 1
    ports:
      - port: 6379
    labels:
      app: "redis-giropops"
      env: "labs"
      live: "false"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
services:
  giropops-senhas:
    ports:
    - port: 5000
      targetPort: 5000
      name: "app"
      serviceType: "NodePort"
      NodePort: 30080 
    - port: 8088
      targetPort: 8088
      name: "metrics"
      serviceType: "ClusterIP"
    labels:
      app: "giropops-senhas"
      env: "labs"
      live: "false"
  redis:
    ports:
    - port: 6379
      targetPort: 6379
      name: "service"
      serviceType: "ClusterIP"
    labels:
      app: "redis-giropops"
      env: "labs"
      live: "false"
observability:
  giropops-senhas:
    logging: true
    metrics:
      enabled: true
      path: "/metrics"
   
  #redis:
databases:
  giropops-senhas:
    mysql:
      host: "mysql.svc.cluster.local"
      port: 3306
      name: "MyDB"
